### ISSUE TITLE
Deployment error with MySolr

### ISSUE THREAD

**Issue by employ** [RedTuna/mysolr#35]
When I try and deploy my server with Mysolr I get this error: **TypeError: 'NoneType' object has no attribute getitem**. It seems like the error is: system_info.raw_content or system_info.raw_content['lucene'] is None
###### Full Log Message

```
Traceback (most recent call last):                                                                   
File "./app/__init__.py", line 70, in <module>                                                     
from app.search.views import search                                                              
File "./app/search/views.py", line 8, in <module>                                                  
solr_search = Search()                                                                           
File "./app/search/search.py", line 81, in __init__                                                
self.solr = Solr(SOLR_URL)                                                                       
File "/xxx/lib/python2.7/site-packages/mysolr/mysolr.py", line 45, in __init__ 
self.version = self.get_version()                                                                
File "/xxx/lib/python2.7/site-packages/mysolr/mysolr.py", line 225, in get_version                                                                                                  
version = system_info.raw_content['lucene']['solr-spec-version']                                 
TypeError: 'NoneType' object has no attribute '__getitem__'                                          
unable to load app 0 (mountpoint='') (callable not found or import error)                            
*** no app loaded. going in full dynamic mode ***
```

**Comment by employ** [comment]
I rolled back to version 0.6 and it seems to work fine

**Comment by moliware** [comment]
What Solr version are you using? Since Solr 4.0 we had to check if we are working with Solr 3.X or 4.X because some requests have changed. So we check the solr version when the Solr object is created (that request is failing as I see in the exception) unless you pass it as a parameter, for instance:

``` python
solr = mysolr.Solr('http://localhost:8983/solr', version=4)
```

To sum up:
- We have to fix that bug.
- You can use the latest version by passing the version parameter.

**Comment by employ** [comment]
I am using version 3.6. Thank you for looking at this, I'm glad I could help find a minor bug :)
